# This is a config for E2B sandbox template.
# You can use template ID (1t25u1vufb80o0s1a6f4) or template name (whatdo-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("whatdo-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("whatdo-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('whatdo-nextjs-test2')

team_id = "6af796d4-5635-4504-b937-a5acdfa44781"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "whatdo-nextjs-test2"
template_id = "1t25u1vufb80o0s1a6f4"
